[2024-04-01T10:36:25.864+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag___fresness.run_model1 scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-04-01T10:36:25.918+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag___fresness.run_model1 scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-04-01T10:36:25.919+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-01T10:36:26.021+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_model1> on 2024-03-25 00:00:00+00:00
[2024-04-01T10:36:26.091+0000] {standard_task_runner.py:60} INFO - Started process 538 to run task
[2024-04-01T10:36:26.131+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag___fresness', 'run_model1', 'scheduled__2024-03-25T00:00:00+00:00', '--job-id', '253', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp0pgh73uq']
[2024-04-01T10:36:26.155+0000] {standard_task_runner.py:88} INFO - Job 253: Subtask run_model1
[2024-04-01T10:36:26.443+0000] {task_command.py:423} INFO - Running <TaskInstance: dag___fresness.run_model1 scheduled__2024-03-25T00:00:00+00:00 [running]> on host 62dc842f1ceb
[2024-04-01T10:36:26.827+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag___fresness' AIRFLOW_CTX_TASK_ID='run_model1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-25T00:00:00+00:00'
[2024-04-01T10:36:26.833+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T10:36:26.845+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --models  --profiles-dir /home/***/.dbt --project-dir /opt/***/proj']
[2024-04-01T10:36:26.974+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T10:37:03.068+0000] {subprocess.py:93} INFO - [0m10:37:03  Running with dbt=1.7.10
[2024-04-01T10:37:06.454+0000] {subprocess.py:93} INFO - [0m10:37:06  Registered adapter: postgres=1.7.10
[2024-04-01T10:37:26.529+0000] {subprocess.py:93} INFO - [0m10:37:26  Found 34 models, 2 operations, 5 tests, 1 source, 0 exposures, 0 metrics, 1407 macros, 0 groups, 0 semantic models
[2024-04-01T10:37:26.548+0000] {subprocess.py:93} INFO - [0m10:37:26  The selection criterion '--profiles-dir' does not match any nodes
[2024-04-01T10:37:26.556+0000] {subprocess.py:93} INFO - [0m10:37:26  Encountered an error:
[2024-04-01T10:37:26.558+0000] {subprocess.py:93} INFO - Non-relative patterns are unsupported
[2024-04-01T10:37:26.567+0000] {subprocess.py:93} INFO - [0m10:37:26  Traceback (most recent call last):
[2024-04-01T10:37:26.570+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 91, in wrapper
[2024-04-01T10:37:26.571+0000] {subprocess.py:93} INFO -     result, success = func(*args, **kwargs)
[2024-04-01T10:37:26.572+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 76, in wrapper
[2024-04-01T10:37:26.574+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:37:26.574+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 169, in wrapper
[2024-04-01T10:37:26.576+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:37:26.576+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 198, in wrapper
[2024-04-01T10:37:26.578+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:37:26.579+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 245, in wrapper
[2024-04-01T10:37:26.580+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:37:26.582+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 278, in wrapper
[2024-04-01T10:37:26.588+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:37:26.593+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/main.py", line 625, in run
[2024-04-01T10:37:26.594+0000] {subprocess.py:93} INFO -     results = task.run()
[2024-04-01T10:37:26.595+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/task/runnable.py", line 454, in run
[2024-04-01T10:37:26.596+0000] {subprocess.py:93} INFO -     self._runtime_initialize()
[2024-04-01T10:37:26.597+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/task/compile.py", line 147, in _runtime_initialize
[2024-04-01T10:37:26.598+0000] {subprocess.py:93} INFO -     super()._runtime_initialize()
[2024-04-01T10:37:26.599+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/task/runnable.py", line 147, in _runtime_initialize
[2024-04-01T10:37:26.602+0000] {subprocess.py:93} INFO -     self.job_queue = self.get_graph_queue()
[2024-04-01T10:37:26.605+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/task/runnable.py", line 140, in get_graph_queue
[2024-04-01T10:37:26.607+0000] {subprocess.py:93} INFO -     return selector.get_graph_queue(spec)
[2024-04-01T10:37:26.609+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 318, in get_graph_queue
[2024-04-01T10:37:26.610+0000] {subprocess.py:93} INFO -     selected_nodes = self.get_selected(spec)
[2024-04-01T10:37:26.611+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 309, in get_selected
[2024-04-01T10:37:26.612+0000] {subprocess.py:93} INFO -     selected_nodes, indirect_only = self.select_nodes(spec)
[2024-04-01T10:37:26.613+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 158, in select_nodes
[2024-04-01T10:37:26.615+0000] {subprocess.py:93} INFO -     direct_nodes, indirect_nodes = self.select_nodes_recursively(spec)
[2024-04-01T10:37:26.616+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in select_nodes_recursively
[2024-04-01T10:37:26.617+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:37:26.622+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in <listcomp>
[2024-04-01T10:37:26.623+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:37:26.624+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in select_nodes_recursively
[2024-04-01T10:37:26.626+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:37:26.627+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in <listcomp>
[2024-04-01T10:37:26.628+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:37:26.629+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in select_nodes_recursively
[2024-04-01T10:37:26.630+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:37:26.631+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in <listcomp>
[2024-04-01T10:37:26.632+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:37:26.634+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 128, in select_nodes_recursively
[2024-04-01T10:37:26.635+0000] {subprocess.py:93} INFO -     direct_nodes, indirect_nodes = self.get_nodes_from_criteria(spec)
[2024-04-01T10:37:26.636+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 82, in get_nodes_from_criteria
[2024-04-01T10:37:26.637+0000] {subprocess.py:93} INFO -     collected = self.select_included(nodes, spec)
[2024-04-01T10:37:26.638+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 68, in select_included
[2024-04-01T10:37:26.640+0000] {subprocess.py:93} INFO -     return set(method.search(included_nodes, spec.value))
[2024-04-01T10:37:26.641+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector_methods.py", line 413, in search
[2024-04-01T10:37:26.642+0000] {subprocess.py:93} INFO -     paths = set(p.relative_to(root) for p in root.glob(selector))
[2024-04-01T10:37:26.643+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector_methods.py", line 413, in <genexpr>
[2024-04-01T10:37:26.645+0000] {subprocess.py:93} INFO -     paths = set(p.relative_to(root) for p in root.glob(selector))
[2024-04-01T10:37:26.646+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/pathlib.py", line 1138, in glob
[2024-04-01T10:37:26.647+0000] {subprocess.py:93} INFO -     raise NotImplementedError("Non-relative patterns are unsupported")
[2024-04-01T10:37:26.648+0000] {subprocess.py:93} INFO - NotImplementedError: Non-relative patterns are unsupported
[2024-04-01T10:37:26.649+0000] {subprocess.py:93} INFO - 
[2024-04-01T10:37:27.909+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-04-01T10:37:27.944+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-04-01T10:37:27.954+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag___fresness, task_id=run_model1, execution_date=20240325T000000, start_date=20240401T103625, end_date=20240401T103727
[2024-04-01T10:37:27.991+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 253 for task run_model1 (Bash command failed. The command returned a non-zero exit code 2.; 538)
[2024-04-01T10:37:28.049+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T10:37:28.163+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
