[2024-04-01T09:51:55.022+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag___dbt.run_model1 scheduled__2024-04-01T02:00:00+00:00 [queued]>
[2024-04-01T09:51:55.133+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag___dbt.run_model1 scheduled__2024-04-01T02:00:00+00:00 [queued]>
[2024-04-01T09:51:55.140+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-04-01T09:51:55.271+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_model1> on 2024-04-01 02:00:00+00:00
[2024-04-01T09:51:55.301+0000] {standard_task_runner.py:60} INFO - Started process 399 to run task
[2024-04-01T09:51:55.328+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag___dbt', 'run_model1', 'scheduled__2024-04-01T02:00:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpf6vfmf31']
[2024-04-01T09:51:55.342+0000] {standard_task_runner.py:88} INFO - Job 97: Subtask run_model1
[2024-04-01T09:51:55.822+0000] {task_command.py:423} INFO - Running <TaskInstance: dag___dbt.run_model1 scheduled__2024-04-01T02:00:00+00:00 [running]> on host 62dc842f1ceb
[2024-04-01T09:51:56.630+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag___dbt' AIRFLOW_CTX_TASK_ID='run_model1' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-01T02:00:00+00:00'
[2024-04-01T09:51:56.642+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T09:51:56.644+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --models  --profiles-dir /home/***/.dbt --project-dir /opt/***/proj']
[2024-04-01T09:51:56.759+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T09:52:33.735+0000] {subprocess.py:93} INFO - [0m09:52:33  Running with dbt=1.7.10
[2024-04-01T09:52:39.129+0000] {subprocess.py:93} INFO - [0m09:52:39  Registered adapter: postgres=1.7.10
[2024-04-01T09:53:15.055+0000] {subprocess.py:93} INFO - [0m09:53:15  Found 34 models, 2 operations, 5 tests, 1 source, 0 exposures, 0 metrics, 1407 macros, 0 groups, 0 semantic models
[2024-04-01T09:53:15.076+0000] {subprocess.py:93} INFO - [0m09:53:15  The selection criterion '--profiles-dir' does not match any nodes
[2024-04-01T09:53:15.080+0000] {subprocess.py:93} INFO - [0m09:53:15  Encountered an error:
[2024-04-01T09:53:15.081+0000] {subprocess.py:93} INFO - Non-relative patterns are unsupported
[2024-04-01T09:53:15.090+0000] {subprocess.py:93} INFO - [0m09:53:15  Traceback (most recent call last):
[2024-04-01T09:53:15.091+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 91, in wrapper
[2024-04-01T09:53:15.093+0000] {subprocess.py:93} INFO -     result, success = func(*args, **kwargs)
[2024-04-01T09:53:15.094+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 76, in wrapper
[2024-04-01T09:53:15.101+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T09:53:15.102+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 169, in wrapper
[2024-04-01T09:53:15.106+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T09:53:15.108+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 198, in wrapper
[2024-04-01T09:53:15.109+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T09:53:15.110+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 245, in wrapper
[2024-04-01T09:53:15.112+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T09:53:15.113+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 278, in wrapper
[2024-04-01T09:53:15.113+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T09:53:15.115+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/main.py", line 625, in run
[2024-04-01T09:53:15.115+0000] {subprocess.py:93} INFO -     results = task.run()
[2024-04-01T09:53:15.116+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/task/runnable.py", line 454, in run
[2024-04-01T09:53:15.118+0000] {subprocess.py:93} INFO -     self._runtime_initialize()
[2024-04-01T09:53:15.119+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/task/compile.py", line 147, in _runtime_initialize
[2024-04-01T09:53:15.120+0000] {subprocess.py:93} INFO -     super()._runtime_initialize()
[2024-04-01T09:53:15.121+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/task/runnable.py", line 147, in _runtime_initialize
[2024-04-01T09:53:15.123+0000] {subprocess.py:93} INFO -     self.job_queue = self.get_graph_queue()
[2024-04-01T09:53:15.125+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/task/runnable.py", line 140, in get_graph_queue
[2024-04-01T09:53:15.127+0000] {subprocess.py:93} INFO -     return selector.get_graph_queue(spec)
[2024-04-01T09:53:15.129+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 318, in get_graph_queue
[2024-04-01T09:53:15.130+0000] {subprocess.py:93} INFO -     selected_nodes = self.get_selected(spec)
[2024-04-01T09:53:15.131+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 309, in get_selected
[2024-04-01T09:53:15.132+0000] {subprocess.py:93} INFO -     selected_nodes, indirect_only = self.select_nodes(spec)
[2024-04-01T09:53:15.134+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 158, in select_nodes
[2024-04-01T09:53:15.135+0000] {subprocess.py:93} INFO -     direct_nodes, indirect_nodes = self.select_nodes_recursively(spec)
[2024-04-01T09:53:15.136+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in select_nodes_recursively
[2024-04-01T09:53:15.137+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T09:53:15.138+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in <listcomp>
[2024-04-01T09:53:15.139+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T09:53:15.140+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in select_nodes_recursively
[2024-04-01T09:53:15.141+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T09:53:15.142+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in <listcomp>
[2024-04-01T09:53:15.143+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T09:53:15.144+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in select_nodes_recursively
[2024-04-01T09:53:15.144+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T09:53:15.146+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in <listcomp>
[2024-04-01T09:53:15.146+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T09:53:15.147+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 128, in select_nodes_recursively
[2024-04-01T09:53:15.148+0000] {subprocess.py:93} INFO -     direct_nodes, indirect_nodes = self.get_nodes_from_criteria(spec)
[2024-04-01T09:53:15.149+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 82, in get_nodes_from_criteria
[2024-04-01T09:53:15.150+0000] {subprocess.py:93} INFO -     collected = self.select_included(nodes, spec)
[2024-04-01T09:53:15.151+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 68, in select_included
[2024-04-01T09:53:15.152+0000] {subprocess.py:93} INFO -     return set(method.search(included_nodes, spec.value))
[2024-04-01T09:53:15.153+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector_methods.py", line 413, in search
[2024-04-01T09:53:15.154+0000] {subprocess.py:93} INFO -     paths = set(p.relative_to(root) for p in root.glob(selector))
[2024-04-01T09:53:15.156+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector_methods.py", line 413, in <genexpr>
[2024-04-01T09:53:15.157+0000] {subprocess.py:93} INFO -     paths = set(p.relative_to(root) for p in root.glob(selector))
[2024-04-01T09:53:15.158+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/pathlib.py", line 1138, in glob
[2024-04-01T09:53:15.159+0000] {subprocess.py:93} INFO -     raise NotImplementedError("Non-relative patterns are unsupported")
[2024-04-01T09:53:15.160+0000] {subprocess.py:93} INFO - NotImplementedError: Non-relative patterns are unsupported
[2024-04-01T09:53:15.161+0000] {subprocess.py:93} INFO - 
[2024-04-01T09:53:16.236+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-04-01T09:53:16.266+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-04-01T09:53:16.277+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag___dbt, task_id=run_model1, execution_date=20240401T020000, start_date=20240401T095155, end_date=20240401T095316
[2024-04-01T09:53:16.315+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 97 for task run_model1 (Bash command failed. The command returned a non-zero exit code 2.; 399)
[2024-04-01T09:53:16.354+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T09:53:16.424+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
