[2024-04-01T10:36:18.161+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag___fresness.run_model1 scheduled__2024-03-20T00:00:00+00:00 [queued]>
[2024-04-01T10:36:18.199+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag___fresness.run_model1 scheduled__2024-03-20T00:00:00+00:00 [queued]>
[2024-04-01T10:36:18.201+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-01T10:36:18.307+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_model1> on 2024-03-20 00:00:00+00:00
[2024-04-01T10:36:18.331+0000] {standard_task_runner.py:60} INFO - Started process 509 to run task
[2024-04-01T10:36:18.361+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag___fresness', 'run_model1', 'scheduled__2024-03-20T00:00:00+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpdiw88df7']
[2024-04-01T10:36:18.383+0000] {standard_task_runner.py:88} INFO - Job 248: Subtask run_model1
[2024-04-01T10:36:18.646+0000] {task_command.py:423} INFO - Running <TaskInstance: dag___fresness.run_model1 scheduled__2024-03-20T00:00:00+00:00 [running]> on host 62dc842f1ceb
[2024-04-01T10:36:19.548+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag___fresness' AIRFLOW_CTX_TASK_ID='run_model1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-20T00:00:00+00:00'
[2024-04-01T10:36:19.573+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T10:36:19.619+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --models  --profiles-dir /home/***/.dbt --project-dir /opt/***/proj']
[2024-04-01T10:36:19.695+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T10:37:02.158+0000] {subprocess.py:93} INFO - [0m10:37:02  Running with dbt=1.7.10
[2024-04-01T10:37:06.060+0000] {subprocess.py:93} INFO - [0m10:37:06  Registered adapter: postgres=1.7.10
[2024-04-01T10:37:25.852+0000] {subprocess.py:93} INFO - [0m10:37:25  Found 34 models, 2 operations, 5 tests, 1 source, 0 exposures, 0 metrics, 1407 macros, 0 groups, 0 semantic models
[2024-04-01T10:37:25.865+0000] {subprocess.py:93} INFO - [0m10:37:25  The selection criterion '--profiles-dir' does not match any nodes
[2024-04-01T10:37:25.870+0000] {subprocess.py:93} INFO - [0m10:37:25  Encountered an error:
[2024-04-01T10:37:25.875+0000] {subprocess.py:93} INFO - Non-relative patterns are unsupported
[2024-04-01T10:37:25.883+0000] {subprocess.py:93} INFO - [0m10:37:25  Traceback (most recent call last):
[2024-04-01T10:37:25.888+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 91, in wrapper
[2024-04-01T10:37:25.889+0000] {subprocess.py:93} INFO -     result, success = func(*args, **kwargs)
[2024-04-01T10:37:25.893+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 76, in wrapper
[2024-04-01T10:37:25.896+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:37:25.898+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 169, in wrapper
[2024-04-01T10:37:25.900+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:37:25.902+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 198, in wrapper
[2024-04-01T10:37:25.903+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:37:25.904+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 245, in wrapper
[2024-04-01T10:37:25.905+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:37:25.906+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 278, in wrapper
[2024-04-01T10:37:25.907+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:37:25.908+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/main.py", line 625, in run
[2024-04-01T10:37:25.910+0000] {subprocess.py:93} INFO -     results = task.run()
[2024-04-01T10:37:25.911+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/task/runnable.py", line 454, in run
[2024-04-01T10:37:25.912+0000] {subprocess.py:93} INFO -     self._runtime_initialize()
[2024-04-01T10:37:25.914+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/task/compile.py", line 147, in _runtime_initialize
[2024-04-01T10:37:25.920+0000] {subprocess.py:93} INFO -     super()._runtime_initialize()
[2024-04-01T10:37:25.923+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/task/runnable.py", line 147, in _runtime_initialize
[2024-04-01T10:37:25.928+0000] {subprocess.py:93} INFO -     self.job_queue = self.get_graph_queue()
[2024-04-01T10:37:25.930+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/task/runnable.py", line 140, in get_graph_queue
[2024-04-01T10:37:25.931+0000] {subprocess.py:93} INFO -     return selector.get_graph_queue(spec)
[2024-04-01T10:37:25.936+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 318, in get_graph_queue
[2024-04-01T10:37:25.939+0000] {subprocess.py:93} INFO -     selected_nodes = self.get_selected(spec)
[2024-04-01T10:37:25.940+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 309, in get_selected
[2024-04-01T10:37:25.945+0000] {subprocess.py:93} INFO -     selected_nodes, indirect_only = self.select_nodes(spec)
[2024-04-01T10:37:25.947+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 158, in select_nodes
[2024-04-01T10:37:25.948+0000] {subprocess.py:93} INFO -     direct_nodes, indirect_nodes = self.select_nodes_recursively(spec)
[2024-04-01T10:37:25.951+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in select_nodes_recursively
[2024-04-01T10:37:25.955+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:37:25.956+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in <listcomp>
[2024-04-01T10:37:25.958+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:37:25.961+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in select_nodes_recursively
[2024-04-01T10:37:25.964+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:37:25.968+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in <listcomp>
[2024-04-01T10:37:25.969+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:37:25.971+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in select_nodes_recursively
[2024-04-01T10:37:25.972+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:37:25.975+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in <listcomp>
[2024-04-01T10:37:25.984+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:37:25.985+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 128, in select_nodes_recursively
[2024-04-01T10:37:25.990+0000] {subprocess.py:93} INFO -     direct_nodes, indirect_nodes = self.get_nodes_from_criteria(spec)
[2024-04-01T10:37:25.993+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 82, in get_nodes_from_criteria
[2024-04-01T10:37:25.995+0000] {subprocess.py:93} INFO -     collected = self.select_included(nodes, spec)
[2024-04-01T10:37:25.997+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 68, in select_included
[2024-04-01T10:37:26.001+0000] {subprocess.py:93} INFO -     return set(method.search(included_nodes, spec.value))
[2024-04-01T10:37:26.004+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector_methods.py", line 413, in search
[2024-04-01T10:37:26.006+0000] {subprocess.py:93} INFO -     paths = set(p.relative_to(root) for p in root.glob(selector))
[2024-04-01T10:37:26.009+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector_methods.py", line 413, in <genexpr>
[2024-04-01T10:37:26.011+0000] {subprocess.py:93} INFO -     paths = set(p.relative_to(root) for p in root.glob(selector))
[2024-04-01T10:37:26.014+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/pathlib.py", line 1138, in glob
[2024-04-01T10:37:26.017+0000] {subprocess.py:93} INFO -     raise NotImplementedError("Non-relative patterns are unsupported")
[2024-04-01T10:37:26.021+0000] {subprocess.py:93} INFO - NotImplementedError: Non-relative patterns are unsupported
[2024-04-01T10:37:26.023+0000] {subprocess.py:93} INFO - 
[2024-04-01T10:37:26.987+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-04-01T10:37:27.022+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-04-01T10:37:27.044+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag___fresness, task_id=run_model1, execution_date=20240320T000000, start_date=20240401T103618, end_date=20240401T103727
[2024-04-01T10:37:27.129+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 248 for task run_model1 (Bash command failed. The command returned a non-zero exit code 2.; 509)
[2024-04-01T10:37:27.157+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T10:37:27.233+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
