[2024-04-01T09:57:19.220+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag___dbt.dbt_data_quality_checks scheduled__2024-03-31T01:00:00+00:00 [queued]>
[2024-04-01T09:57:19.256+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag___dbt.dbt_data_quality_checks scheduled__2024-03-31T01:00:00+00:00 [queued]>
[2024-04-01T09:57:19.258+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-04-01T09:57:19.302+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_data_quality_checks> on 2024-03-31 01:00:00+00:00
[2024-04-01T09:57:19.313+0000] {standard_task_runner.py:60} INFO - Started process 695 to run task
[2024-04-01T09:57:19.320+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag___dbt', 'dbt_data_quality_checks', 'scheduled__2024-03-31T01:00:00+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpvrp62q79']
[2024-04-01T09:57:19.333+0000] {standard_task_runner.py:88} INFO - Job 125: Subtask dbt_data_quality_checks
[2024-04-01T09:57:19.527+0000] {task_command.py:423} INFO - Running <TaskInstance: dag___dbt.dbt_data_quality_checks scheduled__2024-03-31T01:00:00+00:00 [running]> on host 62dc842f1ceb
[2024-04-01T09:57:19.821+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag___dbt' AIRFLOW_CTX_TASK_ID='dbt_data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2024-03-31T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-31T01:00:00+00:00'
[2024-04-01T09:57:19.832+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T09:57:19.834+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /home/***/.dbt --project-dir /opt/***/proj']
[2024-04-01T09:57:19.867+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T09:57:34.365+0000] {subprocess.py:93} INFO - [0m09:57:34  Running with dbt=1.7.10
[2024-04-01T09:57:36.259+0000] {subprocess.py:93} INFO - [0m09:57:36  Registered adapter: postgres=1.7.10
[2024-04-01T09:57:59.013+0000] {subprocess.py:93} INFO - [0m09:57:59  Found 34 models, 2 operations, 5 tests, 1 source, 0 exposures, 0 metrics, 1407 macros, 0 groups, 0 semantic models
[2024-04-01T09:57:59.029+0000] {subprocess.py:93} INFO - [0m09:57:59
[2024-04-01T09:58:00.031+0000] {subprocess.py:93} INFO - [0m09:58:00
[2024-04-01T09:58:00.034+0000] {subprocess.py:93} INFO - [0m09:58:00  Running 1 on-run-start hook
[2024-04-01T09:58:00.457+0000] {subprocess.py:93} INFO - [0m09:58:00  1 of 1 START hook: elementary.on-run-start.0 ................................... [RUN]
[2024-04-01T09:58:00.462+0000] {subprocess.py:93} INFO - [0m09:58:00  1 of 1 OK hook: elementary.on-run-start.0 ...................................... [[32mOK[0m in 0.00s]
[2024-04-01T09:58:00.467+0000] {subprocess.py:93} INFO - [0m09:58:00
[2024-04-01T09:58:00.479+0000] {subprocess.py:93} INFO - [0m09:58:00  Concurrency: 1 threads (target='dev')
[2024-04-01T09:58:00.483+0000] {subprocess.py:93} INFO - [0m09:58:00
[2024-04-01T09:58:00.516+0000] {subprocess.py:93} INFO - [0m09:58:00  1 of 5 START test elementary_freshness_anomalies_raw_orders_creation_date ...... [RUN]
[2024-04-01T09:58:02.577+0000] {subprocess.py:93} INFO - [0m09:58:02  Elementary: Started running data monitors on: POSTGRES.PUBLIC.RAW_ORDERS
[2024-04-01T09:58:04.267+0000] {subprocess.py:93} INFO - [0m09:58:04  Elementary: Finished running data monitors on: POSTGRES.PUBLIC.RAW_ORDERS
[2024-04-01T09:58:07.102+0000] {subprocess.py:93} INFO - [0m09:58:07  1 of 5 PASS elementary_freshness_anomalies_raw_orders_creation_date ............ [[32mPASS[0m in 6.56s]
[2024-04-01T09:58:07.125+0000] {subprocess.py:93} INFO - [0m09:58:07  2 of 5 START test not_null_my_second_dbt_model_id .............................. [RUN]
[2024-04-01T09:58:07.923+0000] {subprocess.py:93} INFO - [0m09:58:07  2 of 5 ERROR not_null_my_second_dbt_model_id ................................... [[31mERROR[0m in 0.79s]
[2024-04-01T09:58:07.967+0000] {subprocess.py:93} INFO - [0m09:58:07  3 of 5 START test not_null_raw_orders_creation_date ............................ [RUN]
[2024-04-01T09:58:09.023+0000] {subprocess.py:93} INFO - [0m09:58:09  3 of 5 PASS not_null_raw_orders_creation_date .................................. [[32mPASS[0m in 1.05s]
[2024-04-01T09:58:09.072+0000] {subprocess.py:93} INFO - [0m09:58:09  4 of 5 START test unique_my_first_dbt_model_id ................................. [RUN]
[2024-04-01T09:58:09.383+0000] {subprocess.py:93} INFO - [0m09:58:09  [31mUnhandled error while executing [0m
[2024-04-01T09:58:09.385+0000] {subprocess.py:93} INFO - [Errno 5] Input/output error: '/opt/***/proj/target/compiled/proj/models/example/schema.yml/unique_my_first_dbt_model_id.sql'
[2024-04-01T09:58:09.446+0000] {subprocess.py:93} INFO - [0m09:58:09  4 of 5 ERROR unique_my_first_dbt_model_id ...................................... [[31mERROR[0m in 0.36s]
[2024-04-01T09:58:09.511+0000] {subprocess.py:93} INFO - [0m09:58:09  5 of 5 START test unique_my_second_dbt_model_id ................................ [RUN]
[2024-04-01T09:58:10.345+0000] {subprocess.py:93} INFO - [0m09:58:10  5 of 5 ERROR unique_my_second_dbt_model_id ..................................... [[31mERROR[0m in 0.79s]
[2024-04-01T09:58:10.719+0000] {subprocess.py:93} INFO - [0m09:58:10
[2024-04-01T09:58:10.731+0000] {subprocess.py:93} INFO - [0m09:58:10  Running 1 on-run-end hook
[2024-04-01T09:58:15.948+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to removed. Terminating instance.
[2024-04-01T09:58:16.046+0000] {process_utils.py:131} INFO - Sending 15 to group 695. PIDs of all processes in the group: [699, 695]
[2024-04-01T09:58:16.068+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 695
[2024-04-01T09:58:16.071+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-01T09:58:16.096+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-04-01T09:58:17.040+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=699, status='terminated', started='09:57:19') (699) terminated with exit code None
[2024-04-01T09:58:17.041+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=695, status='terminated', exitcode=0, started='09:57:18') (695) terminated with exit code 0
